angular.module('eslPluginKeywords', []);

angular.module('eslPluginKeywords')
  .service('keywords', ['$log', function($log) {
    return [
      "possibly",
      "aim",
      "projects",
      "education",
      "semantic",
      'collaboration',
      "permit",
      "accelerate",
      "accumulate",
      "across from",
      "adherence",
      "adornment",
      "aggravate",
      "air conditioning",
      "algorithm",
      "allusion",
      "amateurish",
      "ancient",
      "antiseptic",
      "appallingly",
      "approach",
      "architecture",
      "around-the-clock",
      "ascending",
      "attributable",
      "autograph",
      "backpacker",
      "ballerina",
      "barbarism",
      "basketball",
      "benediction",
      "biblical",
      "billy goat",
      "biweekly",
      "bleachers",
      "bloodless",
      "bombard",
      "breathless",
      "britches",
      "burglary",
      "buttress",
      "Canadian",
      "capital",
      "cartwheel",
      "Catch-22",
      "certifiable",
      "chauvinism",
      "chessboard",
      "chipmunk",
      "circumvention",
      "cleverly",
      "Coast Guard",
      "cologne",
      "communications",
      "complain",
      "con artist",
      "condensation",
      "conflict",
      "conscientious",
      "conspire",
      "contend",
      "contrite",
      "cookout",
      "courtship",
      "cranberry",
      "cuisine",
      "Cyrillic",
      "daredevil",
      "dead end",
      "delicate",
      "demoralize",
      "depreciate",
      "desktop computer",
      "dial tone",
      "disable",
      "disconcert",
      "disgraceful",
      "disobedient",
      "disrupt",
      "distraught",
      "dizziness",
      "double standard",
      "dribble",
      "dungeon",
      "each other",
      "embezzler",
      "empirical",
      "endorsement",
      "enormous",
      "entrance ramp",
      "escalation",
      "etiquette",
      "eviction",
      "excision",
      "exhilarate",
      "experimentally",
      "eyeliner",
      "fantasize",
      "fateful",
      "federalist",
      "fertility",
      "field day",
      "firewood",
      "flavored",
      "flushed",
      "fortune teller",
      "frailty",
      "freight train",
      "frivolity",
      "fucking",
      "gargoyle",
      "gentility",
      "glandular",
      "godfather",
      "goodwill",
      "grade point average",
      "grapefruit",
      "great-grandson",
      "grudging",
      "halftime",
      "hands-on",
      "hard-liner",
      "hatchet",
      "headrest",
      "helpful",
      "high jinks",
      "homonym",
      "horrendous",
      "hot spot",
      "hyphenate",
      "idealism",
      "illiteracy",
      "imminent",
      "imperialism",
      "impress",
      "inasmuch as",
      "inclusive",
      "incremental",
      "indices",
      "industrialist",
      "inference",
      "informality",
      "initiation",
      "inquisitive",
      "inspector",
      "insured",
      "interdependence",
      "intersect",
      "introverted",
      "involved",
      "irritability",
      "jackhammer",
      "John Doe",
      "kindhearted",
      "knockout",
      "law enforcement",
      "liability",
      "life-size",
      "lineage",
      "location",
      "lovingly",
      "lunchbox",
      "maddening",
      "main drag",
      "manslaughter",
      "marketing",
      "measurable",
      "meeting",
      "mentality",
      "metaphorically",
      "Middle Ages",
      "Milky Way",
      "minuscule",
      "misnomer",
      "molding",
      "monorail",
      "morning sickness",
      "motorbike",
      "mundane",
      "mutually",
      "narration",
      "nautical",
      "negligible",
      "newcomer",
      "nightmare",
      "nominally",
      "normality",
      "nursery rhyme",
      "obligatory",
      "officious",
      "ominously",
      "outdoors",
      "outskirts",
      "overhaul",
      "overthrown",
      "papier-mache",
      "parishioner",
      "patient",
      "peppermint",
      "persuade",
      "pharmacology",
      "phrasing",
      "pigheaded",
      "piously",
      "plagiarist",
      "playhouse",
      "pointless",
      "possessive",
      "preacher",
      "preemptive",
      "preregistration",
      "principality",
      "processor",
      "programming",
      "protagonist",
      "prudish",
      "public television",
      "punishment",
      "quarterfinal",
      "rag doll",
      "rattler",
      "receptacle",
      "recover",
      "redskin",
      "refreshments",
      "regularly",
      "release",
      "remittance",
      "reprove",
      "rest home",
      "retiree",
      "romanticize",
      "round-trip",
      "sabotage",
      "sanitary",
      "saunter",
      "science fiction",
      "screech",
      "seasick",
      "security deposit",
      "self-control",
      "semantic",
      "sentimentality",
      "shenanigans",
      "shoplift",
      "showman",
      "sick leave",
      "silently",
      "singing",
      "skydiving",
      "sleeveless",
      "slowpoke",
      "sniffle",
      "soft touch",
      "sometimes",
      "sound bite",
      "spaciousness",
      "specifics",
      "spontaneous",
      "standoff",
      "stature",
      "stereotype",
      "stipend",
      "storeroom",
      "streetcar",
      "substitution",
      "supportive",
      "suspend",
      "symptom",
      "task force",
      "teardrop",
      "terminate",
      "thankless",
      "thoroughness",
      "timekeeper",
      "tortilla",
      "transatlantic",
      "traumatic",
      "turnover",
      "two-dimensional",
      "umpteen",
      "uncharacteristically",
      "underneath",
      "undying",
      "unidentified",
      "unmarked",
      "untruthful",
      "valuables",
      "vertical",
      "vigilante",
      "visibility",
      "voluntarily",
      "waiting room",
      "warlike",
      "watchman",
      "wealthy",
      "well-behaved",
      "wharves",
      "widower",
      "withhold",
      "yearning"
    ]
  }]);

